### ISSUE TITLE
How does the data in coef_ look like?

### ISSUE THREAD

**Issue by rmasand1** [iit-cs579/main#296] opened 2016-10-21 16:11 UTC
Hi I am doing the top_coef and I am confused about the data is stored in it and how the mapping is done because when I am iterating over it is having positive and negative values and how are we supposed to map it to vocab??

**Comment by aronwc** [comment] 2016-10-21 20:46
E.g., if:
```python
>>> clf.coef_[0]
array([-2, 5, 10.6])
```
And vocab is:
```python
{'a': 0, 'b': 1, 'c': 2}
```
Then that means that feature 'a' has coefficient -2, 'b' has coefficient 5, and 'c' has coefficient 2.
Positive coefficients are predictive of class 1, negative coefficients are predictive of class 0.

**Comment by rmasand1** [comment] 2016-10-21 21:02
So will that mean positive will be in clf.coef_[1] and negative will be in clf.coef_[0] ?

**Comment by vjonnala** [comment] 2016-10-21 21:06
yup .

**Comment by saiarjuntanguturi** [comment] 2016-10-21 21:11
No. 
clf.coef_[0] contains an array with the coefficients corresponding to each column. 
Your goal here is to sort this coefficient array, but before you sort it, associate each coefficient with the feature it corresponds to from vocab (via a tuple/list/etc.). I think professor meant:
""Then that means that feature 'a' has coefficient -2, 'b' has coefficient 5, and 'c' has coefficient **10.6**.
Positive coefficients are predictive of class 1, negative coefficients are predictive of class 0.""
in his comment, since a corresponds to column 0, b to column 1, c to column 2.

**Comment by Shringa13** [comment] 2016-10-21 21:25
While passing value as clf.coef_[1] code is throwing error of Index 1 is out of bounds for axis 0 with size 1.
I am not getting this error.
While I print clf.coef_ it gives me data in a single row that means clf.coef_ has only value at 0th index only.

**Comment by AndrewLu1992** [comment] 2016-10-21 21:25
Since there are only 2 classes needed to predict, I doubt if coef_ is a 2darray and then you don't have the option like coef_[1].

**Comment by Shringa13** [comment] 2016-10-21 21:29
Yes,you are right . coef_ is an 1Darray then how we are going to predict for 2 classes i.e. positive and negative words?

**Comment by vmanikes** [comment] 2016-10-21 21:30
@vjonnala and the negative will be in ?

**Comment by AndrewLu1992** [comment] 2016-10-21 21:31
The reason is that for the binary classification task, you only need a hyperplane to distinguish all labels points into 2 different regions which are characterized by a vector of coefficients. The decision plane is wTx, where w is the coef_ and x is vocabularies(variables). 
if w[i] is negative, it means that the corresponding word is pushing the answer to the second class and if w[i] is positive contributes to a bigger number of the outcome which in turn pushing the result to the first class.

**Comment by AndrewLu1992** [comment] 2016-10-21 21:37
@Shringa13  You are right.

**Comment by AndrewLu1992** [comment] 2016-10-21 21:43
And if we need to predict N classes( N > 2). Then coef_ will become a 2darray of shape(N - 1, # of features + 1). Each row represents a hyperplane that separates of a class from all the other.

**Comment by Shringa13** [comment] 2016-10-21 21:45
@AndrewLu1992 Thank you so much. Only problem now is my output is not matching with what presebt in Log.txt. All tokens are completely different

**Comment by saiarjuntanguturi** [comment] 2016-10-21 21:54
coef_[0] contains all the coefficients. Let me give you an example:
Assuming there are 7 words in your vocabulary:
vocab = {'a' : 0, 'b' : 1, 'c' : 2 .... 'f' : 6}
coef_[0] => [0.5 ,0.6 ,0.7 ,-0.5 ,-0.6 ,-0.7]
Then 0.5 is the coefficient of 'a', which means 'a' is pushing documents towards the positive class (which is 1, which means positive sentiment in our assignment)
Also -0.7 is the coefficient of 'f' which means 'f' is pushing documents towards the negative class (which is 0 in our assignment, and means negative sentiment)
Keep in mind vocab does not have to be ordered (dicts in python are not ordered). You have to find a way to associate the word at column 0 with the 0th coefficient in coef_[0]. Once this association has been done, you can sort by coefficient values.

**Comment by AndrewLu1992** [comment] 2016-10-21 22:03
@Shringa13 this may be caused by other errors in your previous functions. Check if you have tokenized right. And also check if coef_[0] actually represents a word in the vocabulary. coef_[0] usually represents intercept of the hyperplane and you need to start your map from coef[1] if this is true.

**Closed** 2016-10-22 03:43 UTC
